# Generated by Django 3.2.4 on 2022-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=1000)),
                ('image_link', models.CharField(max_length=500)),
            ],
        ),
    ]
